### ISSUE TITLE
Unable to authorize on Android

### ISSUE THREAD

**Issue by chuckbergeron** [walletlink/walletlink#15]
Hello 👋 !

We are attempting to add the WalletLink integration to Pool Together, however on Android after scanning the QR code it says "Authorize on Wallet App" but the authorization dialogue never appears, even after waiting a long period of time.

We tried uninstalling and reinstalling the Wallet app with no luck, as well as deleting the `__WalletLink__:https://www.walletlink.org:SessionId` cookie from the browser.

Also tested it out on iPhones and sometimes it does work, but the auth message can take 20 - 30 seconds to appear at times.

The specific version of our app we are using to test with is https://staging.pooltogether.us/ - You can click 'Connect Wallet' in the top-right corner to try our implementation.

Cheers, thanks.

**Comment by clementbalestrat** [comment]
@chuckbergeron any update on this issue? I'm currently experiencing it.

**Comment by chuckbergeron** [comment]
I believe this had to do with an improper Avatar image in our config.
