### ISSUE TITLE
Retrieve user's address without infura

### ISSUE THREAD

**Issue by whois0xio** [walletlink/walletlink#16]
In my case, I need just the user address. To prevent copy/paste, i would use walletlink. 

I made a prototype but with the infura limitation, I wouldn't provide my infura key on a frontend app.

**Comment by petejkim** [comment]
I'd suggest creating a separate free INFURA project for the purposes of this

**Comment by fabianbusch** [comment]
@whois0xio You could also use white-listing for your Infura key. So only your app-domain can use the key. 😊
