### ISSUE TITLE
Unable to change chainId from default (1)

### ISSUE THREAD

**Issue by tunneling** [walletlink/walletlink#195]
I'm trying a very simple test and would like to connect to Ropsten. However, I am unable to set the chainId to 3.

Here's a snippet of the code followed by the results in the browser console. The getChainid() method returns chainId = 1.

```   
console.log('Begin WalletLink Test');
const providerUri =
   'https://ropsten.infura.io/v3/c9f7ef8004d24059bbb6add7a505d393';
const chainId = 3;
const walletLink = new WalletLink({
   appName: 'Test App',
   appLogoUrl:
      'https://bit.ly/3GiusyH',
   darkMode: false,
    });
window.ethereum = walletLink.makeWeb3Provider(providerUri, chainId);
console.log(window.ethereum);
console.log('window.ethereum.getChainId', window.ethereum.getChainId());
console.log('End WalletLink Test ');
```

![image](https://user-images.githubusercontent.com/4457051/138613179-1b2dec9d-d193-4cb3-8c16-08b8b4c8b588.png)

**Comment by brendanww** [comment]
@tunneling that chainId value passed in is ignored. switch the chainId by using the `default network` menu within settings on either of the mobile clients
