### ISSUE TITLE
SVG images in "try extension" modal broken on master

### ISSUE THREAD

**Issue by zeptonaut** [walletlink/walletlink#212]
### What are the steps to reproduce?
1. Bring up the walletlink modal for Coinbase

### What's expected?
The modal should come up with all images in it working, e.g.

![image](https://user-images.githubusercontent.com/1407397/142652498-8d40eb81-16a6-4271-897c-44f729a5e7ac.png)

(This screenshot is taken from version 2.2.7.)

### What actually happens?
The inline SVGs in the above image are all broken:

![image](https://user-images.githubusercontent.com/1407397/142653204-af1cc9ef-bfc9-4f34-8dd5-bbc8134c9e25.png)

### Why is this happening?
My guess is that the new SVG optimizer added in https://github.com/walletlink/walletlink/commit/03f5b34d13f10a567bfed3d737a1397354c0c4fb isn't correctly inlining the SVGs. When you use Chrome inspect to actually look at the HTML, it looks like the leading `data:image/svg+xml` is missing.

### Are other sites experiencing this?
Yes - you can see for example that https://app.influence.vote/#/ is experiencing the issue on their public site.

**Comment by klujanrosas** [comment]
@zeptonaut I opened #226 to fix this, first time contributing to this repo so not sure who needs to review.
