### ISSUE TITLE
walletlink how to  integration 

### ISSUE THREAD

**Issue by shrinivasmani** [walletlink/walletlink#22]
http://www.helloaltcoins.com/#!/trade/BCT-ETH
i have add walletlink code in index.html (main page )
i have already install 
# With Yarn
yarn add walletlink
# With NPM
npm install walletlink

this command 
but does not work 
please have look

<script>

// TypeScript
import WalletLink from "walletlink"
import Web3 from "web3"

const APP_NAME = "helloaltcoins"
const APP_LOGO_URL = "http://www.helloaltcoins.com/images/logo256.png"
const ETH_JSONRPC_URL = "https://mainnet.infura.io/v3/261afee99a634b7586757e162f6b38cf"
const CHAIN_ID = 1

// Initialize WalletLink
export const WalletLink = new WalletLink({
  appName: APP_NAME,
  appLogoUrl: APP_LOGO_URL
  
})

// Initialize a Web3 Provider object
export const ethereum = walletLink.makeWeb3Provider(ETH_JSONRPC_URL, CHAIN_ID)

// Initialize a Web3 object
export const web3 = new Web3(ethereum as any)

// Optionally, have the default account be set automatically when available
ethereum.on("accountsChanged", (accounts: string[]) => {
  web3.eth.defaultAccount = accounts[0]
})
web3.eth.defaultAccount = web3.eth.accounts[0]

// Use eth_RequestAccounts
ethereum.send("eth_requestAccounts").then((accounts: string[]) => {
  console.log(`User's address is ${accounts[0]}`)

})

// Alternatively, you can use ethereum.enable()
ethereum.enable().then((accounts: string[]) => {
  console.log(`User's address is ${accounts[0]}`)
})
</script>
can you please enplane proper solution  and provide proper code included wlletlink  button
thanks

**Comment by petejkim** [comment]
The example is in TypeScript, please use JavaScript. To use the WalletLink, you will have to include WalletLink npm module in your app as a dependency.
