### ISSUE TITLE
Account change detection does not work

### ISSUE THREAD

**Issue by nicolaswww** [walletlink/walletlink#23]
I'm listening to the accountsChanged event but the change detection doesn't work (Web3 - browser).
This event works with Metamask for example.

**Comment by petejkim** [comment]
It's gone as of 2.0. Address should not change, it's fixed per connection. To obtain address, please use EIP1102. Thank you!

**Comment by leleroma** [comment]
👍👍👍👍

**Comment by Keith1650** [comment]
Ho
