### ISSUE TITLE
No way to disconnect from dapp

### ISSUE THREAD

**Issue by nategeier** [walletlink/walletlink#24]
### Bug Description  
No way to disconnect from the dapp or mobile iOS

### Steps to Reproduce
1. Press disconnect on CoinbaseWallet and the localStorage remains on the dapp

### Expected Behavior
Disconnect after pressing disconnect.
What I really want is that there is no way to disconnect on the dapp.

WalletConnect handles it really well with a simple:
```
await provider.close()
```

This throws an error as the function does not exists.

**Comment by petejkim** [comment]
You can now disconnect either by doing `walletLink.disconnect()` or `provider.close()`
