### ISSUE TITLE
'disconnect' Event Listener

### ISSUE THREAD

**Issue by aaronbarnardsound** [walletlink/walletlink#25]
As far as I can tell, there is no way to know in a Dapp if the user has disconnected the session via the advanced settings in the Coinbase wallet app. It would be great to be able to subscribe to a disconnection event so that the dapp can handle it:

```javascript
provider.on('disconnect', () => {
// handle disconnect
})
```

Currently, if a user does disconnect from a session, and then if the Dapp tries to initiate a transaction, it will show the popup with a pending state. After a certain amount of time it will give the option to reconnect. When that is clicked, the connection modal pops up, but then the page automatically refreshes. Is this intended behavior?

**Comment by petejkim** [comment]
With the latest version of WalletLink (2.x) and the latest version of Coinbase Wallet for iOS (21.1.368), disconnection from either side should be handled automatically. Android version of Coinbase Wallet that handles disconnections will be available in the next release.

**Comment by aaronbarnardsound** [comment]
@petejkim How will the dapp side know that the disconnection has occurred and how is it handled automatically? As per the second part of my comment above, the page is refreshed for some reason when "reconnect" is clicked. Is this meant to happen and is how it is handled automatically?

**Comment by petejkim** [comment]
Have you upgraded to WalletLink 2.0?

With WL 2.0, the next time the dapp is loaded, WL2 will detect that the connection is marked as disconnected, and clear the state.

**Comment by pi0neerpat** [comment]
I can confirm this works. Thanks for adding it!

**Comment by aaronbarnardsound** [comment]
Yes is all working on my end, thanks for this @petejkim 👍
