### ISSUE TITLE
Next.js issue: ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by jigglyjams** [walletlink/walletlink#259]
Hello! I am trying to integrate WalletLink in a Next.js append keep getting the following error:
`error - ReferenceError: localStorage is not defined`

I have used yarn to add walletlink as a dependency and am simply trying to initialize as shown in the readme with:
```
  // Initialize WalletLink
  const walletLink = new WalletLink({
    appName: APP_NAME,
    appLogoUrl: APP_LOGO_URL,
    darkMode: false
  })
```

Anything I am missing?

Thanks!

**Comment by cb-jake** [comment]
👋  @jigglyjams. Next.js is server rendered and WalletLink relies on the window object and browser specific apis, like `localStorage`.

One approach would be instantiate WalletLink inside of a `useEffect` or `componentDidMount`. Hope that helps.

Going to close for now.

**Comment by slavanga** [comment]
Just ran into this issue using RainbowKit. The solution was adding `ssr: true` to my config:

```js
import { getDefaultConfig } from '@rainbow-me/rainbowkit';

const config = getDefaultConfig({
  appName: 'My RainbowKit App',
  projectId: 'YOUR_PROJECT_ID',
  chains: [mainnet, polygon, optimism, arbitrum, base, zora],
  ssr: true, // If your dApp uses server side rendering (SSR)
});
```

**Comment by dzek69** [comment]
The same fix as @slavanga proposed (adding `ssr: true`) works with **wagmi** as well
