### ISSUE TITLE
No network checking or alerts (danger!)

### ISSUE THREAD

**Issue by pi0neerpat** [walletlink/walletlink#39]
### Issue

Currently there is no network check when making a transaction request. This could mean losing funds (!!) for a developer who is testing using another network. 

### Steps to reproduce

```js
const ETH_JSONRPC_URL = `https://mainnet.infura.io/v3/${infuraKey}`;
const CHAIN_ID = 1;
const ethereum = walletLink.makeWeb3Provider(ETH_JSONRPC_URL, CHAIN_ID);
```

Change your test wallet network to something besides mainnet. Then push any transaction to the wallet.

### Possible solution 
- There should be some indicator that the network for the transaction is mainnet. This is only really relevant while on a testnet, so normal users would never see it,

**Comment by brendanww** [comment]
We display the network name in transaction modals on all clients now.
