### ISSUE TITLE
Add support for EIP1193 + test networks

### ISSUE THREAD

**Issue by pi0neerpat** [walletlink/walletlink#41]
### Issue

1. Test networks are not supported
2. Cannot detect when the network is changed by the user (related to #39 )

### Code snippet

No matter what I do, I cannot seem to unlock the wallet using any network other than mainnet (homestead). And when switch networks in the app, the function is never called,  which suggests that EIP1193 hasn't been implemented.

`@walletconnect/web3-provider` v1.0.13
`walletlink` ^2.0.2
Coinbase Wallet v22.3.307

```js
import { Web3Provider } from "@ethersproject/providers";
import WalletLink from "walletlink";

export const unlockWalletLink = async ({
  infuraKey,
  debug,
  targetNetwork,
  onNetworkChange
}) => {
  const ETH_JSONRPC_URL = `https://mainnet.infura.io/v3/${infuraKey}`;
  try {
    const walletLink = new WalletLink({
      appName: APP_NAME,
      appLogoUrl: APP_LOGO_URL,
    });
    const ethereum = walletLink.makeWeb3Provider(
      ETH_JSONRPC_URL,
      42 // targetNetwork ? getIdFromName(targetNetwork) : 1
    );
    const walletProvider = new Web3Provider(ethereum);
    const accounts = await ethereum.enable();

    // Issue #1, this is always homestead
    const network = await walletProvider.getNetwork();

    // Issue #2, onNetworkChange is never called
    walletProvider.on("chainChanged", onNetworkChange);
```

### Discussion 

EIP1193 has already been implemented in MetaMask [link](https://docs.metamask.io/guide/ethereum-provider.html#events) and WalletConnect [link](https://docs.walletconnect.org/quick-start/dapps/web3-provider#events-eip-1193)

This update would be really helpful for testing purposes, and I appreciate your support

**Comment by pi0neerpat** [comment]
I tried the legacy `walletProvider.on("networkChanged", onNetworkChange);` as well but no luck

**Comment by brendanww** [comment]
we now support handling both addEthereumChain/switchEthereumChain requests to allow dapps to request network changes. the clients are also able to update the network via the settings menu.

**Comment by pi0neerpat** [comment]
Sweet looking forward to trying this out soon!
