### ISSUE TITLE
Walletlink + etherjs?

### ISSUE THREAD

**Issue by Benjythebee** [walletlink/walletlink#75]
Is there any plans to support etherjs? it's a much faster and lighter library than web3...

**Comment by alisscco** [comment]
First time I’m seeing it .. it’s actually really good although integration.
What did you have mind ?

**Comment by zaeguerra** [comment]
Same thought.

**Comment by petejkim** [comment]
Does initializing ethers with WalletLinkProvider not work for you?

**Comment by Benjythebee** [comment]
> Does initializing ethers with WalletLinkProvider not work for you?

What do you mean? `WalletLinkProvider` is not an option as a provider?

However I got it to work using 
```js
let walletlink = walletLink.makeWeb3Provider(ETH_JSONRPC_URL, CHAIN_ID)
this.provider = new ethers.providers.Web3Provider(walletlink , 'any')

accounts = await walletlink.request({ method: 'eth_requestAccounts' })
```
It successfully creates a provider. and I can obtain accounts.
However, that provider is super broken.
For example, If I decide to check the chainId I'm currently connected to :
```js
this.provider = new ethers.providers.Web3Provider(walletlink , 'any')
// (using metamask)
this.provider.network //returns {name: "homestead", chainId: 1, ensAddress: ".....", _defaultProvider: ƒ}
await this.provider.getNetwork() //returns {name: "homestead", chainId: 1, ensAddress: ".....", _defaultProvider: ƒ}

// using wallellink
this.provider.network //returns undefined
await this.provider.getNetwork() // (apparently doesn't exist) => Error: could not detect network (chainId="[object Object]",
  ```

ethers also has the `app.provider._networkPromise` function which I guess is used internally and running that function returns the following (in the console for walletlink):

```
Promise { <state>: "rejected", <reason>: Error }
​
<state>: "rejected"
<reason>: Error: ​could not detect network (chainId="[object Object]", event="invalidNetwork", serverError="Error: invalid BigNumber value (argument=\"value\", value=\"[object Object]\", code=INVALID_ARGUMENT, version=bignumber/5.3.0)", code=NETWORK_ERROR, version=providers/5.3.1

```

**Comment by Benjythebee** [comment]
Ok, I think I was at fault here. When doing
```
this.provider = new ethers.providers.Web3Provider(walletlink , 'any')
```
walletlink was somehow badly instanciated. It seems to work nicely now
![image](https://user-images.githubusercontent.com/38708022/122158962-a0664900-cec1-11eb-81ac-c6ad8cd2279e.png)

**Comment by dwcoen123** [comment]
What is this? Daniel Wayne coen

**Comment by dwcoen123** [comment]
[ETH address]
0x981da518c405f33846018186abfe13491850f482

Daniel wayne coen

**Comment by dddd8888z** [comment]
What is this? Daniel Wayne coen
